version: "3"
services:
  redis:
    image: redis
    container_name: "bugmanager_storage_redis"
  backend:
    build: ./backend-api/.
    container_name: "bugmanager_backend"
    env_file: ./backend-api/.env
  nginx:
    build: 
      context: .
      dockerfile: Dockerfile-development-nginx
    container_name: "bugmanager_nginx"
    ports:
      - "9000:80"