version: "3"
services:
  redis:
    image: redis
    container_name: "bugmanager_storage_redis"
  mongo:
    image: mongo
    container_name: "bugmanager_storage_mongo"
    volumes:
      - db-data:/data/db
  backend:
    build: ./backend-api/.
    container_name: "bugmanager_backend"
    env_file: ./backend-api/.env
  nginx:
    build: 
      context: .
      dockerfile: Dockerfile-development-nginx
    container_name: "bugmanager_nginx"
    ports:
      - "9000:80"